### ISSUE TITLE
ADS-B reported aircraft shown outside DI circumference 

### ISSUE THREAD

**Issue by jbswindle** [UnexplodedMinds/RoscoPi#1]
Low priority
![p1040652](https://user-images.githubusercontent.com/33461157/51282801-bfd4b100-19ab-11e9-8125-2af14432fdbf.JPG)
 item: Aircraft shown on display not confined to inner circumference of the DI and may show in the AI portion of the display.

**Comment by UnexplodedMinds** [comment]
I'll need to add that as an option.  One user indicated they preferred it that way.

**Comment by UnexplodedMinds** [comment]
Feature added beside the traffic button to toggle displaying outside the heading indicator.
