### ISSUE TITLE
Altimeter shows Pressure Altitude

### ISSUE THREAD

**Issue by dns-007** [UnexplodedMinds/RoscoPi#3]
On the Altimeter on the upper right corner the Pressure Altitude is used. This will not give the correct altitude over MSL, but the Altitude in the ISO Standard atmosphere.
Please change this to use the GPS Altitude above MSL. Change BaroPressureAltitude to GPSAltitudeMSL

**Comment by UnexplodedMinds** [comment]
It's currently using GPS altitude since that's all that's available from the Stratux.  A sensor platform is being developed to provide true pressure altitude that will use the Stratux as an AP to send the data to Stratofier.
